### ISSUE TITLE
Error While running demo script

### ISSUE THREAD

**Issue by ashishgupta2598** [MichalBusta/E2E-MLT#64]
make: Entering directory '/media/ai/ashish/OCR/mrz_newTest/E2E-MLT/nms'
make: 'adaptor.so' is up to date.
make: Leaving directory '/media/ai/ashish/OCR/mrz_newTest/E2E-MLT/nms'
Traceback (most recent call last):
Command- python3 demo.py -model=e2e-mlt.h5
Error-:
```
File "/media/ai/ashish/OCR/mrz_newTest/E2E-MLT/net_utils.py", line 30, in load_net
    v.copy_(param)
RuntimeError: The expanded size of the tensor (8400) must match the existing size (7500) at non-singleton dimension 0
Traceback (most recent call last):
  File "/media/ai/ashish/OCR/mrz_newTest/E2E-MLT/net_utils.py", line 30, in load_net
    v.copy_(param)
RuntimeError: The expanded size of the tensor (8400) must match the existing size (7500) at non-singleton dimension 0
e2e-mlt.h5
Using cuda ...
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
```

**Comment by duxiangcheng** [comment]
I have met the same problem. Have you solved it？
thanks！

**Comment by duxiangcheng** [comment]
@ashishgupta2598 I have met the same problem. Have you solved it？

**Comment by MichalBusta** [comment]
#49

**Comment by duxiangcheng** [comment]
@MichalBusta  Thank you! But the error is "can't open camera by index". Can you give me some advice?

**Comment by duxiangcheng** [comment]
@MichalBusta  thank you !

**Comment by MichalBusta** [comment]
On 27/03/2020 13:42, duxiangcheng wrote:
>
> @MichalBusta <https://github.com/MichalBusta> Thank you! But the error 
> is "can't open camera by index". Can you give me some advice?
>
opencv stuff (not related to project) - can be caused by:

  - you are trying  to open non-existing camera

  - your opencv is not compiled with v4l support

no stacktrace, no help, sorry

**Comment by ashishgupta2598** [comment]
> I have met the same problem. Have you solved it？
> thanks！

@duxiangcheng No!! I am still figuring out !!!

**Comment by AniketGurav** [comment]
There are 2 pre-trained models 1. e2e-mlt 2. e2e-mlt-rctw
I guess you are using 1st one. 
Try the 2nd model mentioned above The link for downloading it is given on the main page.
